export const mockedObject = [
    {
        key: 1,
        objectType: "МКД",
        district: "Московский",
        objectCategory: "objectCategory",
        adm_area: "Восточный административный округ",
        street: "Измайловский бульвар",
        typeOfWork: "Ремонт крыши",
        house: "47",
        address: "Измайловский бульвар, 47",
        planDate: "12.06.2023",
        UNOM: "8625"
    },
    {
        key: 2,
        objectType: "МКД",
        district: "Измайлово",
        objectCategory: "objectCategory",
        adm_area: "Восточный административный округ",
        street: "Парковая 6-я",
        house: "29Б",
        typeOfWork: "Ремонт крыши",
        address: "Парковая 6-я, 29 Б",
        planDate: "22.01.2022",
        UNOM: "18655"
    },
    {
        key: 3,
        objectType: "МКД",
        district: "Измайлово Восточное",
        objectCategory: "objectCategory",
        adm_area: "Восточный административный округ",
        street: "Нижняя Первомайская",
        house: "62",
        typeOfWork: "Ремонт крыши",
        address: "Нижняя Первомайская 62",
        planDate: "22.01.2022",
        UNOM: "19325"
    },
    {
        key: 4,
        objectType: "МКД",
        district: "Измайлово Восточное",
        objectCategory: "objectCategory",
        adm_area: "Восточный административный округ",
        street: "Нижняя Первомайская",
        house: "49",
        address: "Нижняя Первомайская, 49",
        typeOfWork: "Ремонт крыши",
        planDate: "17.02.2022",
        UNOM: "19248"
    },
    {
        key: 5,
        objectType: "МКД",
        district: "Измайлово",
        objectCategory: "objectCategory",
        adm_area: "Восточный административный округ",
        street: "Парковая 7-я",
        house: "19",
        typeOfWork: "Ремонт крыши",
        address: "Парковая 7-я, 19",
        planDate: "17.02.2022",
        UNOM: "18680"
    },
    {
        key: 6,
        objectType: "МКД",
        district: "Богородское",
        objectCategory: "objectCategory",
        adm_area: "Восточный административный округ",
        street: "Подбельского",
        house: "22",
        planDate: "17.02.2022",
        address: "Подбельского, 22",
        typeOfWork: "Ремонт крыши",
        UNOM: "20203"
    },
    {
        key: 7,
        objectType: "МКД",
        district: "Измайлово",
        objectCategory: "objectCategory",
        adm_area: "Восточный административный округ",
        street: "Парковая 16-я",
        house: "7",
        planDate: "02.02.2022",
        typeOfWork: "Ремонт крыши",
        address: "Парковая 16-я, 7",
        UNOM: "18985"
    },
    {
        key: 8,
        objectType: "МКД",
        district: "Измайлово Восточное",
        objectCategory: "objectCategory",
        adm_area: "Восточный административный округ",
        street: "Первомайская",
        house: "128/9",
        typeOfWork: "Ремонт крыши",
        address: "Первомайская 128/9",
        planDate: "17.02.2022",
        UNOM: "19226"
    },
    {
        key: 9,
        objectType: "МКД",
        district: "Гольяново",
        objectCategory: "objectCategory",
        adm_area: "Восточный административный округ",
        street: "Щелковское",
        house: "57",
        address: "Щелковское, 57",
        planDate: "09.01.2022",
        typeOfWork: "Ремонт крыши",
        UNOM: "29934"
    },
    {
        key: 10,
        objectType: "МКД",
        district: "Гольяново",
        objectCategory: "objectCategory",
        adm_area: "Восточный административный округ",
        street: "Парковая 6-я",
        house: "20/53",
        planDate: "09.01.2022",
        typeOfWork: "Ремонт крыши",
        address: "Парковая 6-я",
        UNOM: "18648"
    }
];