export const mockedObject = [
    {
        key: 1,
        name: "Mike",
        age: 32,
        address: "10 Downing Street",
        cadastralNumber: "2",
        objectType: "Жилой дом",
        exploitationYear: "2023",
        condition: "Хорошее",
        district: "Московский",
        objectCategory: "objectCategory",
        adm_area: "adm_ares",
        street: "street",
        house: "house",
    },
    {
        key: 2,
        name: "John",
        age: 42,
        address: "10 Downing Street",
        cadastralNumber: "2",
        objectType: "Жилой дом",
        exploitationYear: "2023",
        condition: "Хорошее",
        district: "Московский",
        objectCategory: "objectCategory",
        adm_area: "adm_ares",
        street: "street",
        house: "house",
    },
    {
        key: 3,
        name: "Mike",
        age: 32,
        address: "10 Downing Street",
        cadastralNumber: "2",
        objectType: "Жилой дом",
        exploitationYear: "2023",
        condition: "Хорошее",
        district: "Московский",
        objectCategory: "objectCategory",
        adm_area: "adm_ares",
        street: "street",
        house: "house",
    },
    {
        key: 4,
        name: "John",
        age: 42,
        address: "10 Downing Street",
        cadastralNumber: "2",
        objectType: "Жилой дом",
        exploitationYear: "2023",
        condition: "Хорошее",
        district: "Московский",
        objectCategory: "objectCategory",
        adm_area: "adm_ares",
        street: "street",
        house: "house",
    },
    {
        key: 5,
        name: "Mike",
        age: 32,
        address: "10 Downing Street",
        cadastralNumber: "2",
        objectType: "Жилой дом",
        exploitationYear: "2023",
        condition: "Хорошее",
        district: "Московский",
        objectCategory: "objectCategory",
        adm_area: "adm_ares",
        street: "street",
        house: "house",
    },
];