#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES_ML_USER LOGIN PASSWORD '$POSTGRES_ML_PASSWORD' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION VALID UNTIL 'infinity';
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $POSTGRES_ML_USER;
    GRANT USAGE ON SCHEMA public TO $POSTGRES_ML_USER;
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO $POSTGRES_ML_USER;
EOSQL