version: '3'

services:
  postgres_db:
    container_name: postgres_db
    image:
      postgres:13.4-alpine
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "20m"
    env_file:
      - envs/database.env
    restart:
      on-failure
    networks:
      - pgdb

  backend:
    container_name: backend
    image: { { env.BACKEND_IMAGE } }
    ports:
      - 8000:8000
    depends_on:
      - postgres_db
    env_file:
      - envs/database.env
    restart:
      on-failure
    networks:
      - pgdb
      - front_back

  ml:
    image: {{ env.ML_IMAGE }}
    depends_on:
      - postgres_db
    env_file:
      - envs/database.env
    restart:
      on-failure
    networks:
      - pgdb

  frontend:
    image: {{ env.FRONTEND_IMAGE }}
    ports:
      - 3000:3000
    depends_on:
      - backend
    restart:
      on-failure
    networks:
      - front_back

networks:
  pgdb:
  front_back: