name: Tests on any push and merge event
on:
  push:
    branches:
      - '**'
  pull_request:
    types: [closed]
jobs:
  build-docker:
    if: github.event_name=='push' || github.event.pull_request.merged == true
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Run build
        run: docker-compose build